### ISSUE TITLE
blank pages when downloading large pdfs on scribd

### ISSUE THREAD

**Issue by fel1xjh** [rkwyu/scribd-dl#2] opened 2024-09-11 14:18 UTC
When I'm downloading a 300-page document, it stops at 270. The remaining are blank pages.

**Comment by rkwyu** [comment] 2024-10-04 16:30
Could you please provide a sample document url for investigation?

**Comment by rkwyu** [comment] 2024-12-05 20:18
This issue is a duplicate of #4. Closing this in favor of the original.

**Closed by rkwyu** 2024-12-05 20:18 UTC
Labels: bug
